#!/bin/zsh

sudo tar -czvpf /mnt/backup/backup_$(date +"%Y%m%d").tgz --exclude='/home/alex/Música' --exclude='/home/alex/.config' --exclude='/home/alex/.cache' --exclude='/home/alex/VirtualBox\ VMs' /home/alex/
